drop database if exists capstone;
create database capstone;
use capstone;

drop table if exists Posts;
drop table if exists WatchList;
drop table if exists Users;

create table Users (
	id INT auto_increment primary key,
	username VARCHAR(25),
	password VARCHAR(25),
	bio TEXT
);

create table WatchList (
	id INT auto_increment primary key,
	currency_name VARCHAR(20),
	user_id INT
);

create table Posts (
	id INT auto_increment primary key,
	title VARCHAR(255),
	body TEXT,
	user_id INT
);

insert into Users (username, password, bio) values ('user1', 'user1', 'quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce');
insert into Users (username, password, bio) values ('user2', 'user2', 'dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum');
insert into Users (username, password, bio) values ('user3', 'user3', 'at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue');
insert into Users (username, password, bio) values ('user4', 'user4', 'est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non');
insert into Users (username, password, bio) values ('user5', 'user5', 'pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam');
insert into Users (username, password, bio) values ('user6', 'user6', 'neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac');
insert into Users (username, password, bio) values ('krakestraw6', 'H30UjAKOREHg', 'lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia');
insert into Users (username, password, bio) values ('iloudon7', 'evL0OTTrA', 'ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien');
insert into Users (username, password, bio) values ('emaharg8', 'NI5I2Ne', 'aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus');
insert into Users (username, password, bio) values ('dupwood9', 'kNrXqGUQKc5', 'eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis');
insert into Users (username, password, bio) values ('fconsidinea', 'HIjL2e', 'sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum');
insert into Users (username, password, bio) values ('sivakhnob', 'wfGHC3ZEj4', 'risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis');
insert into Users (username, password, bio) values ('emattockc', 'wnJO7YQTSVyZ', 'in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at');
insert into Users (username, password, bio) values ('afranklingd', 'bVScVpP', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium');
insert into Users (username, password, bio) values ('mtalle', 'TaPqvQM235lI', 'neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet');
insert into Users (username, password, bio) values ('apoluzzif', 'SHNrzkTZFEtJ', 'orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium');
insert into Users (username, password, bio) values ('mgrigolong', 'XfIOHJdRNP', 'ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus');
insert into Users (username, password, bio) values ('pkensith', 'v5sq6U', 'quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum');
insert into Users (username, password, bio) values ('mshelbornei', 'yIebn5q6ZEtw', 'lorem ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut');
insert into Users (username, password, bio) values ('acaj', 'LkpR8EcM8MKn', 'habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis');
insert into Users (username, password, bio) values ('rhugk', 'nRyrvonLGf', 'ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus');
insert into Users (username, password, bio) values ('ldifrancecshil', 'S7zpSr', 'congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor');
insert into Users (username, password, bio) values ('nsartenm', 'sCqc6fnj', 'in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien');
insert into Users (username, password, bio) values ('kendleyn', 'NCHrtLr', 'lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel');
insert into Users (username, password, bio) values ('osturgesso', 'AsN5fr1SDZo', 'pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non');
insert into Users (username, password, bio) values ('akimmincep', '6kOLp1', 'vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id');
insert into Users (username, password, bio) values ('jmikalskiq', 'MvaOjul8tHd', 'lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget');
insert into Users (username, password, bio) values ('gthiesr', 'GoQSwJ', 'primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat');
insert into Users (username, password, bio) values ('aharnors', 'RHP0Xa1szLH', 'lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit');
insert into Users (username, password, bio) values ('tbrotherst', 'ESLcPVD', 'magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing');
insert into Users (username, password, bio) values ('mtwidaleu', 'CmXGQoj', 'eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas');
insert into Users (username, password, bio) values ('trobertelliv', 'TDzjP10cEp', 'erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut');
insert into Users (username, password, bio) values ('ikillbyw', 'v0X0EbkY', 'interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus');
insert into Users (username, password, bio) values ('sbiesterfeldx', '1oRiUhSd7', 'felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque');
insert into Users (username, password, bio) values ('wscotsony', 'ngD9m3l', 'vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo');
insert into Users (username, password, bio) values ('ctedorenkoz', '9mQSEj04', 'maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam');
insert into Users (username, password, bio) values ('ekyme10', 'QLJJVPp', 'amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu');
insert into Users (username, password, bio) values ('edraisey11', 'u2jK7h36T', 'ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum');
insert into Users (username, password, bio) values ('aocarran12', 'YwLW8UgQgfQ', 'tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac');
insert into Users (username, password, bio) values ('slovelace13', 'XyKRxCM', 'vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus');
insert into Users (username, password, bio) values ('aelward14', '9rhHmZg', 'vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius');
insert into Users (username, password, bio) values ('deusden15', 'gDT8jbM', 'etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque');
insert into Users (username, password, bio) values ('srottery16', 'Bjc2xNcEsal', 'nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque');
insert into Users (username, password, bio) values ('sshambrooke17', 'zFSoU1', 'ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus');
insert into Users (username, password, bio) values ('bpatman18', 'DYxNmEIjIMs', 'lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non');
insert into Users (username, password, bio) values ('gmckue19', 'e6DNFGh0rBXt', 'justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna');
insert into Users (username, password, bio) values ('gkiff1a', 'zwe02E', 'consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis');
insert into Users (username, password, bio) values ('oevett1b', 'kNcGe3hA1', 'non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend');
insert into Users (username, password, bio) values ('gvitte1c', 'uz8gcuUd', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc');
insert into Users (username, password, bio) values ('mhuggon1d', 'be3aGtocBO', 'tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce');

insert into WatchList (currency_name, user_id) values ('casper', 32);
insert into WatchList (currency_name, user_id) values ('compound', 20);
insert into WatchList (currency_name, user_id) values ('dogecoin', 30);
insert into WatchList (currency_name, user_id) values ('algorand', 25);
insert into WatchList (currency_name, user_id) values ('fantom', 11);
insert into WatchList (currency_name, user_id) values ('ethereum', 43);
insert into WatchList (currency_name, user_id) values ('avalanche', 8);
insert into WatchList (currency_name, user_id) values ('decentraland', 46);
insert into WatchList (currency_name, user_id) values ('ethereum', 11);
insert into WatchList (currency_name, user_id) values ('decentraland', 35);
insert into WatchList (currency_name, user_id) values ('ethereum', 30);
insert into WatchList (currency_name, user_id) values ('tether', 37);
insert into WatchList (currency_name, user_id) values ('ethereum', 7);
insert into WatchList (currency_name, user_id) values ('tron', 2);
insert into WatchList (currency_name, user_id) values ('stellar', 12);
insert into WatchList (currency_name, user_id) values ('casper', 10);
insert into WatchList (currency_name, user_id) values ('stellar', 9);
insert into WatchList (currency_name, user_id) values ('stellar', 24);
insert into WatchList (currency_name, user_id) values ('avalanche', 39);
insert into WatchList (currency_name, user_id) values ('ravencoin', 11);
insert into WatchList (currency_name, user_id) values ('cardano', 5);
insert into WatchList (currency_name, user_id) values ('bitcoin', 27);
insert into WatchList (currency_name, user_id) values ('dogecoin', 32);
insert into WatchList (currency_name, user_id) values ('algorand', 28);
insert into WatchList (currency_name, user_id) values ('shiba-inu', 23);
insert into WatchList (currency_name, user_id) values ('tron', 48);
insert into WatchList (currency_name, user_id) values ('compound', 19);
insert into WatchList (currency_name, user_id) values ('solana', 33);
insert into WatchList (currency_name, user_id) values ('dogecoin', 13);
insert into WatchList (currency_name, user_id) values ('dogecoin', 48);
insert into WatchList (currency_name, user_id) values ('tron', 37);
insert into WatchList (currency_name, user_id) values ('tron', 5);
insert into WatchList (currency_name, user_id) values ('stellar', 1);
insert into WatchList (currency_name, user_id) values ('algorand', 10);
insert into WatchList (currency_name, user_id) values ('decentraland', 50);
insert into WatchList (currency_name, user_id) values ('ethereum', 28);
insert into WatchList (currency_name, user_id) values ('polygon', 41);
insert into WatchList (currency_name, user_id) values ('algorand', 28);
insert into WatchList (currency_name, user_id) values ('tron', 48);
insert into WatchList (currency_name, user_id) values ('ravencoin', 46);
insert into WatchList (currency_name, user_id) values ('dogecoin', 39);
insert into WatchList (currency_name, user_id) values ('algorand', 10);
insert into WatchList (currency_name, user_id) values ('compound', 2);
insert into WatchList (currency_name, user_id) values ('tether', 25);
insert into WatchList (currency_name, user_id) values ('avalanche', 31);
insert into WatchList (currency_name, user_id) values ('gemini-dollar', 22);
insert into WatchList (currency_name, user_id) values ('zcash', 36);
insert into WatchList (currency_name, user_id) values ('stellar', 10);
insert into WatchList (currency_name, user_id) values ('tether', 25);
insert into WatchList (currency_name, user_id) values ('algorand', 49);
insert into WatchList (currency_name, user_id) values ('tron', 28);
insert into WatchList (currency_name, user_id) values ('casper', 3);
insert into WatchList (currency_name, user_id) values ('avalanche', 30);
insert into WatchList (currency_name, user_id) values ('avalanche', 31);
insert into WatchList (currency_name, user_id) values ('tether', 26);
insert into WatchList (currency_name, user_id) values ('polygon', 5);
insert into WatchList (currency_name, user_id) values ('avalanche', 50);
insert into WatchList (currency_name, user_id) values ('avalanche', 18);
insert into WatchList (currency_name, user_id) values ('polygon', 3);
insert into WatchList (currency_name, user_id) values ('avalanche', 26);
insert into WatchList (currency_name, user_id) values ('tether', 30);
insert into WatchList (currency_name, user_id) values ('avalanche', 21);
insert into WatchList (currency_name, user_id) values ('tron', 36);
insert into WatchList (currency_name, user_id) values ('gemini-dollar', 46);
insert into WatchList (currency_name, user_id) values ('algorand', 23);
insert into WatchList (currency_name, user_id) values ('ravencoin', 1);
insert into WatchList (currency_name, user_id) values ('tether', 42);
insert into WatchList (currency_name, user_id) values ('dogecoin', 21);
insert into WatchList (currency_name, user_id) values ('stellar', 3);
insert into WatchList (currency_name, user_id) values ('stellar', 20);
insert into WatchList (currency_name, user_id) values ('ravencoin', 4);
insert into WatchList (currency_name, user_id) values ('ravencoin', 20);
insert into WatchList (currency_name, user_id) values ('gemini-dollar', 37);
insert into WatchList (currency_name, user_id) values ('casper', 6);
insert into WatchList (currency_name, user_id) values ('fantom', 33);
insert into WatchList (currency_name, user_id) values ('bitcoin', 34);
insert into WatchList (currency_name, user_id) values ('polygon', 29);
insert into WatchList (currency_name, user_id) values ('compound', 19);
insert into WatchList (currency_name, user_id) values ('casper', 49);
insert into WatchList (currency_name, user_id) values ('bitcoin', 12);
insert into WatchList (currency_name, user_id) values ('casper', 21);
insert into WatchList (currency_name, user_id) values ('bitcoin', 26);
insert into WatchList (currency_name, user_id) values ('tron', 10);
insert into WatchList (currency_name, user_id) values ('casper', 17);
insert into WatchList (currency_name, user_id) values ('fantom', 19);
insert into WatchList (currency_name, user_id) values ('zcash', 4);
insert into WatchList (currency_name, user_id) values ('decentraland', 27);
insert into WatchList (currency_name, user_id) values ('zcash', 21);
insert into WatchList (currency_name, user_id) values ('zcash', 15);
insert into WatchList (currency_name, user_id) values ('avalanche', 33);
insert into WatchList (currency_name, user_id) values ('shiba-inu', 34);
insert into WatchList (currency_name, user_id) values ('polygon', 36);
insert into WatchList (currency_name, user_id) values ('tether', 18);
insert into WatchList (currency_name, user_id) values ('zcash', 11);
insert into WatchList (currency_name, user_id) values ('tether', 23);
insert into WatchList (currency_name, user_id) values ('zcash', 33);
insert into WatchList (currency_name, user_id) values ('dogecoin', 25);
insert into WatchList (currency_name, user_id) values ('algorand', 25);
insert into WatchList (currency_name, user_id) values ('stellar', 18);
insert into WatchList (currency_name, user_id) values ('algorand', 7);
insert into WatchList (currency_name, user_id) values ('dogecoin', 37);
insert into WatchList (currency_name, user_id) values ('chainlink', 8);
insert into WatchList (currency_name, user_id) values ('ethereum', 46);
insert into WatchList (currency_name, user_id) values ('solana', 28);
insert into WatchList (currency_name, user_id) values ('dogecoin', 41);
insert into WatchList (currency_name, user_id) values ('shiba-inu', 9);
insert into WatchList (currency_name, user_id) values ('stellar', 37);
insert into WatchList (currency_name, user_id) values ('ravencoin', 7);
insert into WatchList (currency_name, user_id) values ('fantom', 34);
insert into WatchList (currency_name, user_id) values ('bitcoin', 3);
insert into WatchList (currency_name, user_id) values ('bitcoin', 14);
insert into WatchList (currency_name, user_id) values ('polygon', 21);
insert into WatchList (currency_name, user_id) values ('ravencoin', 6);
insert into WatchList (currency_name, user_id) values ('decentraland', 49);
insert into WatchList (currency_name, user_id) values ('ravencoin', 17);
insert into WatchList (currency_name, user_id) values ('fantom', 11);
insert into WatchList (currency_name, user_id) values ('chainlink', 37);
insert into WatchList (currency_name, user_id) values ('chainlink', 44);
insert into WatchList (currency_name, user_id) values ('shiba-inu', 37);
insert into WatchList (currency_name, user_id) values ('avalanche', 42);
insert into WatchList (currency_name, user_id) values ('zcash', 39);
insert into WatchList (currency_name, user_id) values ('compound', 35);
insert into WatchList (currency_name, user_id) values ('shiba-inu', 8);
insert into WatchList (currency_name, user_id) values ('algorand', 34);
insert into WatchList (currency_name, user_id) values ('casper', 20);
insert into WatchList (currency_name, user_id) values ('decentraland', 31);
insert into WatchList (currency_name, user_id) values ('cardano', 38);
insert into WatchList (currency_name, user_id) values ('shiba-inu', 13);
insert into WatchList (currency_name, user_id) values ('ravencoin', 31);
insert into WatchList (currency_name, user_id) values ('tron', 25);
insert into WatchList (currency_name, user_id) values ('dogecoin', 36);
insert into WatchList (currency_name, user_id) values ('polygon', 22);
insert into WatchList (currency_name, user_id) values ('ravencoin', 6);
insert into WatchList (currency_name, user_id) values ('stellar', 36);
insert into WatchList (currency_name, user_id) values ('avalanche', 5);
insert into WatchList (currency_name, user_id) values ('gemini-dollar', 10);
insert into WatchList (currency_name, user_id) values ('algorand', 11);
insert into WatchList (currency_name, user_id) values ('decentraland', 44);
insert into WatchList (currency_name, user_id) values ('stellar', 9);
insert into WatchList (currency_name, user_id) values ('ravencoin', 43);
insert into WatchList (currency_name, user_id) values ('solana', 10);
insert into WatchList (currency_name, user_id) values ('bitcoin', 22);
insert into WatchList (currency_name, user_id) values ('shiba-inu', 42);
insert into WatchList (currency_name, user_id) values ('casper', 38);
insert into WatchList (currency_name, user_id) values ('avalanche', 6);
insert into WatchList (currency_name, user_id) values ('shiba-inu', 49);
insert into WatchList (currency_name, user_id) values ('decentraland', 38);
insert into WatchList (currency_name, user_id) values ('avalanche', 9);
insert into WatchList (currency_name, user_id) values ('tether', 46);
insert into WatchList (currency_name, user_id) values ('algorand', 18);
insert into WatchList (currency_name, user_id) values ('chainlink', 17);
insert into WatchList (currency_name, user_id) values ('ethereum', 17);
insert into WatchList (currency_name, user_id) values ('casper', 45);
insert into WatchList (currency_name, user_id) values ('polygon', 27);
insert into WatchList (currency_name, user_id) values ('solana', 19);
insert into WatchList (currency_name, user_id) values ('polygon', 49);
insert into WatchList (currency_name, user_id) values ('zcash', 47);
insert into WatchList (currency_name, user_id) values ('ethereum', 27);
insert into WatchList (currency_name, user_id) values ('bitcoin', 14);
insert into WatchList (currency_name, user_id) values ('chainlink', 10);
insert into WatchList (currency_name, user_id) values ('bitcoin', 37);
insert into WatchList (currency_name, user_id) values ('gemini-dollar', 36);
insert into WatchList (currency_name, user_id) values ('fantom', 30);
insert into WatchList (currency_name, user_id) values ('fantom', 47);
insert into WatchList (currency_name, user_id) values ('polygon', 28);
insert into WatchList (currency_name, user_id) values ('compound', 12);
insert into WatchList (currency_name, user_id) values ('avalanche', 3);
insert into WatchList (currency_name, user_id) values ('polygon', 6);
insert into WatchList (currency_name, user_id) values ('fantom', 22);
insert into WatchList (currency_name, user_id) values ('tether', 25);
insert into WatchList (currency_name, user_id) values ('solana', 2);
insert into WatchList (currency_name, user_id) values ('avalanche', 17);
insert into WatchList (currency_name, user_id) values ('fantom', 31);
insert into WatchList (currency_name, user_id) values ('tether', 49);
insert into WatchList (currency_name, user_id) values ('dogecoin', 18);
insert into WatchList (currency_name, user_id) values ('shiba-inu', 31);
insert into WatchList (currency_name, user_id) values ('tron', 30);
insert into WatchList (currency_name, user_id) values ('stellar', 37);
insert into WatchList (currency_name, user_id) values ('ethereum', 6);
insert into WatchList (currency_name, user_id) values ('dogecoin', 38);
insert into WatchList (currency_name, user_id) values ('bitcoin', 49);
insert into WatchList (currency_name, user_id) values ('bitcoin', 21);
insert into WatchList (currency_name, user_id) values ('bitcoin', 12);
insert into WatchList (currency_name, user_id) values ('shiba-inu', 25);
insert into WatchList (currency_name, user_id) values ('avalanche', 45);
insert into WatchList (currency_name, user_id) values ('decentraland', 36);
insert into WatchList (currency_name, user_id) values ('ravencoin', 19);
insert into WatchList (currency_name, user_id) values ('tether', 39);
insert into WatchList (currency_name, user_id) values ('compound', 26);
insert into WatchList (currency_name, user_id) values ('cardano', 36);
insert into WatchList (currency_name, user_id) values ('tron', 46);
insert into WatchList (currency_name, user_id) values ('ethereum', 43);
insert into WatchList (currency_name, user_id) values ('ethereum', 20);
insert into WatchList (currency_name, user_id) values ('decentraland', 50);
insert into WatchList (currency_name, user_id) values ('ravencoin', 9);
insert into WatchList (currency_name, user_id) values ('tron', 7);
insert into WatchList (currency_name, user_id) values ('gemini-dollar', 44);
insert into WatchList (currency_name, user_id) values ('solana', 5);
insert into WatchList (currency_name, user_id) values ('algorand', 16);
insert into WatchList (currency_name, user_id) values ('compound', 6);
insert into WatchList (currency_name, user_id) values ('decentraland', 19);
insert into WatchList (currency_name, user_id) values ('polygon', 38);
insert into WatchList (currency_name, user_id) values ('cardano', 28);
insert into WatchList (currency_name, user_id) values ('avalanche', 15);
insert into WatchList (currency_name, user_id) values ('ethereum', 23);
insert into WatchList (currency_name, user_id) values ('casper', 45);
insert into WatchList (currency_name, user_id) values ('tron', 41);
insert into WatchList (currency_name, user_id) values ('avalanche', 1);
insert into WatchList (currency_name, user_id) values ('avalanche', 11);
insert into WatchList (currency_name, user_id) values ('stellar', 27);
insert into WatchList (currency_name, user_id) values ('tron', 8);
insert into WatchList (currency_name, user_id) values ('fantom', 3);
insert into WatchList (currency_name, user_id) values ('shiba-inu', 23);
insert into WatchList (currency_name, user_id) values ('solana', 48);
insert into WatchList (currency_name, user_id) values ('ethereum', 31);
insert into WatchList (currency_name, user_id) values ('stellar', 41);
insert into WatchList (currency_name, user_id) values ('compound', 46);
insert into WatchList (currency_name, user_id) values ('tether', 43);
insert into WatchList (currency_name, user_id) values ('ethereum', 22);
insert into WatchList (currency_name, user_id) values ('tether', 25);
insert into WatchList (currency_name, user_id) values ('algorand', 42);
insert into WatchList (currency_name, user_id) values ('casper', 21);
insert into WatchList (currency_name, user_id) values ('zcash', 32);
insert into WatchList (currency_name, user_id) values ('casper', 49);
insert into WatchList (currency_name, user_id) values ('stellar', 6);
insert into WatchList (currency_name, user_id) values ('algorand', 18);
insert into WatchList (currency_name, user_id) values ('tether', 13);
insert into WatchList (currency_name, user_id) values ('cardano', 38);
insert into WatchList (currency_name, user_id) values ('fantom', 11);
insert into WatchList (currency_name, user_id) values ('avalanche', 39);
insert into WatchList (currency_name, user_id) values ('decentraland', 22);
insert into WatchList (currency_name, user_id) values ('algorand', 47);
insert into WatchList (currency_name, user_id) values ('gemini-dollar', 34);
insert into WatchList (currency_name, user_id) values ('ravencoin', 31);
insert into WatchList (currency_name, user_id) values ('cardano', 47);
insert into WatchList (currency_name, user_id) values ('avalanche', 39);
insert into WatchList (currency_name, user_id) values ('tron', 21);
insert into WatchList (currency_name, user_id) values ('chainlink', 15);
insert into WatchList (currency_name, user_id) values ('bitcoin', 8);
insert into WatchList (currency_name, user_id) values ('shiba-inu', 36);
insert into WatchList (currency_name, user_id) values ('compound', 37);
insert into WatchList (currency_name, user_id) values ('ravencoin', 15);
insert into WatchList (currency_name, user_id) values ('solana', 43);
insert into WatchList (currency_name, user_id) values ('compound', 21);
insert into WatchList (currency_name, user_id) values ('solana', 41);
insert into WatchList (currency_name, user_id) values ('bitcoin', 14);
insert into WatchList (currency_name, user_id) values ('avalanche', 17);
insert into WatchList (currency_name, user_id) values ('tether', 44);
insert into WatchList (currency_name, user_id) values ('zcash', 42);
insert into WatchList (currency_name, user_id) values ('chainlink', 42);
insert into WatchList (currency_name, user_id) values ('polygon', 37);
insert into WatchList (currency_name, user_id) values ('avalanche', 34);
insert into WatchList (currency_name, user_id) values ('gemini-dollar', 8);
insert into WatchList (currency_name, user_id) values ('bitcoin', 4);
insert into WatchList (currency_name, user_id) values ('chainlink', 46);
insert into WatchList (currency_name, user_id) values ('stellar', 33);
insert into WatchList (currency_name, user_id) values ('tether', 40);
insert into WatchList (currency_name, user_id) values ('tether', 27);
insert into WatchList (currency_name, user_id) values ('cardano', 28);
insert into WatchList (currency_name, user_id) values ('bitcoin', 43);
insert into WatchList (currency_name, user_id) values ('shiba-inu', 27);
insert into WatchList (currency_name, user_id) values ('bitcoin', 11);
insert into WatchList (currency_name, user_id) values ('fantom', 11);
insert into WatchList (currency_name, user_id) values ('fantom', 12);
insert into WatchList (currency_name, user_id) values ('casper', 11);
insert into WatchList (currency_name, user_id) values ('ethereum', 9);
insert into WatchList (currency_name, user_id) values ('chainlink', 29);
insert into WatchList (currency_name, user_id) values ('ethereum', 4);
insert into WatchList (currency_name, user_id) values ('solana', 3);
insert into WatchList (currency_name, user_id) values ('stellar', 39);
insert into WatchList (currency_name, user_id) values ('avalanche', 9);
insert into WatchList (currency_name, user_id) values ('fantom', 22);
insert into WatchList (currency_name, user_id) values ('zcash', 32);
insert into WatchList (currency_name, user_id) values ('tron', 15);
insert into WatchList (currency_name, user_id) values ('tron', 48);
insert into WatchList (currency_name, user_id) values ('ethereum', 30);
insert into WatchList (currency_name, user_id) values ('zcash', 23);
insert into WatchList (currency_name, user_id) values ('bitcoin', 47);
insert into WatchList (currency_name, user_id) values ('decentraland', 41);
insert into WatchList (currency_name, user_id) values ('polygon', 12);
insert into WatchList (currency_name, user_id) values ('fantom', 44);
insert into WatchList (currency_name, user_id) values ('bitcoin', 35);
insert into WatchList (currency_name, user_id) values ('stellar', 21);
insert into WatchList (currency_name, user_id) values ('tron', 3);
insert into WatchList (currency_name, user_id) values ('decentraland', 10);
insert into WatchList (currency_name, user_id) values ('avalanche', 19);
insert into WatchList (currency_name, user_id) values ('dogecoin', 11);
insert into WatchList (currency_name, user_id) values ('zcash', 18);
insert into WatchList (currency_name, user_id) values ('polygon', 24);
insert into WatchList (currency_name, user_id) values ('bitcoin', 10);
insert into WatchList (currency_name, user_id) values ('casper', 3);
insert into WatchList (currency_name, user_id) values ('bitcoin', 8);
insert into WatchList (currency_name, user_id) values ('chainlink', 3);
insert into WatchList (currency_name, user_id) values ('bitcoin', 16);
insert into WatchList (currency_name, user_id) values ('shiba-inu', 40);
insert into WatchList (currency_name, user_id) values ('chainlink', 10);
insert into WatchList (currency_name, user_id) values ('tron', 46);
insert into WatchList (currency_name, user_id) values ('decentraland', 42);
insert into WatchList (currency_name, user_id) values ('algorand', 4);
insert into WatchList (currency_name, user_id) values ('dogecoin', 2);
insert into WatchList (currency_name, user_id) values ('decentraland', 44);
insert into WatchList (currency_name, user_id) values ('ravencoin', 10);
insert into WatchList (currency_name, user_id) values ('decentraland', 10);
insert into WatchList (currency_name, user_id) values ('dogecoin', 18);
insert into WatchList (currency_name, user_id) values ('casper', 33);
insert into WatchList (currency_name, user_id) values ('stellar', 34);
insert into WatchList (currency_name, user_id) values ('polygon', 35);
insert into WatchList (currency_name, user_id) values ('avalanche', 41);
insert into WatchList (currency_name, user_id) values ('fantom', 43);
insert into WatchList (currency_name, user_id) values ('tron', 27);
insert into WatchList (currency_name, user_id) values ('ravencoin', 35);
insert into WatchList (currency_name, user_id) values ('chainlink', 30);
insert into WatchList (currency_name, user_id) values ('ravencoin', 42);
insert into WatchList (currency_name, user_id) values ('chainlink', 7);
insert into WatchList (currency_name, user_id) values ('fantom', 4);
insert into WatchList (currency_name, user_id) values ('algorand', 36);
insert into WatchList (currency_name, user_id) values ('shiba-inu', 21);
insert into WatchList (currency_name, user_id) values ('bitcoin', 12);
insert into WatchList (currency_name, user_id) values ('fantom', 34);
insert into WatchList (currency_name, user_id) values ('algorand', 46);
insert into WatchList (currency_name, user_id) values ('tron', 16);
insert into WatchList (currency_name, user_id) values ('ethereum', 6);
insert into WatchList (currency_name, user_id) values ('ethereum', 27);
insert into WatchList (currency_name, user_id) values ('gemini-dollar', 16);
insert into WatchList (currency_name, user_id) values ('algorand', 43);
insert into WatchList (currency_name, user_id) values ('chainlink', 6);
insert into WatchList (currency_name, user_id) values ('ethereum', 29);
insert into WatchList (currency_name, user_id) values ('fantom', 32);
insert into WatchList (currency_name, user_id) values ('polygon', 8);
insert into WatchList (currency_name, user_id) values ('polygon', 49);
insert into WatchList (currency_name, user_id) values ('zcash', 31);
insert into WatchList (currency_name, user_id) values ('casper', 37);
insert into WatchList (currency_name, user_id) values ('casper', 31);
insert into WatchList (currency_name, user_id) values ('polygon', 26);
insert into WatchList (currency_name, user_id) values ('ravencoin', 10);
insert into WatchList (currency_name, user_id) values ('polygon', 26);
insert into WatchList (currency_name, user_id) values ('dogecoin', 41);
insert into WatchList (currency_name, user_id) values ('zcash', 19);
insert into WatchList (currency_name, user_id) values ('decentraland', 13);
insert into WatchList (currency_name, user_id) values ('casper', 44);
insert into WatchList (currency_name, user_id) values ('stellar', 42);
insert into WatchList (currency_name, user_id) values ('compound', 7);
insert into WatchList (currency_name, user_id) values ('polygon', 21);
insert into WatchList (currency_name, user_id) values ('cardano', 13);
insert into WatchList (currency_name, user_id) values ('zcash', 48);
insert into WatchList (currency_name, user_id) values ('ravencoin', 34);
insert into WatchList (currency_name, user_id) values ('polygon', 33);
insert into WatchList (currency_name, user_id) values ('stellar', 10);
insert into WatchList (currency_name, user_id) values ('stellar', 22);
insert into WatchList (currency_name, user_id) values ('dogecoin', 19);
insert into WatchList (currency_name, user_id) values ('tron', 20);
insert into WatchList (currency_name, user_id) values ('dogecoin', 23);
insert into WatchList (currency_name, user_id) values ('algorand', 24);
insert into WatchList (currency_name, user_id) values ('cardano', 30);
insert into WatchList (currency_name, user_id) values ('solana', 10);
insert into WatchList (currency_name, user_id) values ('fantom', 41);
insert into WatchList (currency_name, user_id) values ('solana', 3);
insert into WatchList (currency_name, user_id) values ('tether', 2);
insert into WatchList (currency_name, user_id) values ('zcash', 46);
insert into WatchList (currency_name, user_id) values ('chainlink', 23);
insert into WatchList (currency_name, user_id) values ('fantom', 6);
insert into WatchList (currency_name, user_id) values ('avalanche', 44);
insert into WatchList (currency_name, user_id) values ('dogecoin', 27);
insert into WatchList (currency_name, user_id) values ('tether', 36);
insert into WatchList (currency_name, user_id) values ('decentraland', 20);
insert into WatchList (currency_name, user_id) values ('ethereum', 34);
insert into WatchList (currency_name, user_id) values ('bitcoin', 20);
insert into WatchList (currency_name, user_id) values ('shiba-inu', 40);
insert into WatchList (currency_name, user_id) values ('bitcoin', 25);
insert into WatchList (currency_name, user_id) values ('compound', 26);
insert into WatchList (currency_name, user_id) values ('solana', 30);
insert into WatchList (currency_name, user_id) values ('tether', 48);
insert into WatchList (currency_name, user_id) values ('ethereum', 28);
insert into WatchList (currency_name, user_id) values ('zcash', 10);
insert into WatchList (currency_name, user_id) values ('decentraland', 42);
insert into WatchList (currency_name, user_id) values ('tron', 47);
insert into WatchList (currency_name, user_id) values ('tether', 38);
insert into WatchList (currency_name, user_id) values ('dogecoin', 35);
insert into WatchList (currency_name, user_id) values ('polygon', 38);
insert into WatchList (currency_name, user_id) values ('zcash', 41);
insert into WatchList (currency_name, user_id) values ('cardano', 49);
insert into WatchList (currency_name, user_id) values ('cardano', 30);
insert into WatchList (currency_name, user_id) values ('algorand', 1);
insert into WatchList (currency_name, user_id) values ('tether', 12);
insert into WatchList (currency_name, user_id) values ('ethereum', 23);
insert into WatchList (currency_name, user_id) values ('ethereum', 14);
insert into WatchList (currency_name, user_id) values ('algorand', 6);
insert into WatchList (currency_name, user_id) values ('zcash', 45);
insert into WatchList (currency_name, user_id) values ('polygon', 49);
insert into WatchList (currency_name, user_id) values ('tron', 6);
insert into WatchList (currency_name, user_id) values ('shiba-inu', 14);
insert into WatchList (currency_name, user_id) values ('tron', 38);
insert into WatchList (currency_name, user_id) values ('chainlink', 19);
insert into WatchList (currency_name, user_id) values ('ethereum', 34);
insert into WatchList (currency_name, user_id) values ('shiba-inu', 31);
insert into WatchList (currency_name, user_id) values ('ravencoin', 45);
insert into WatchList (currency_name, user_id) values ('bitcoin', 11);
insert into WatchList (currency_name, user_id) values ('compound', 18);
insert into WatchList (currency_name, user_id) values ('avalanche', 50);
insert into WatchList (currency_name, user_id) values ('decentraland', 2);

insert into Posts (title, body, user_id) values ('id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio', 'nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum', 28);
insert into Posts (title, body, user_id) values ('vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa', 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer', 25);
insert into Posts (title, body, user_id) values ('aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus', 'quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa', 23);
insert into Posts (title, body, user_id) values ('ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam', 'at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis', 40);
insert into Posts (title, body, user_id) values ('vel lectus in quam fringilla rhoncus mauris enim leo rhoncus', 'libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla', 26);
insert into Posts (title, body, user_id) values ('hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum', 'ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede', 17);
insert into Posts (title, body, user_id) values ('in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius', 'dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec', 18);
insert into Posts (title, body, user_id) values ('sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus', 'sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui', 36);
insert into Posts (title, body, user_id) values ('ultrices phasellus id sapien in sapien iaculis congue vivamus metus', 'nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi', 50);
insert into Posts (title, body, user_id) values ('quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id', 'in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam', 5);
insert into Posts (title, body, user_id) values ('lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus', 'nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque', 3);
insert into Posts (title, body, user_id) values ('pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue', 'quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam', 21);
insert into Posts (title, body, user_id) values ('fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices', 27);
insert into Posts (title, body, user_id) values ('sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in', 'libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus', 43);
insert into Posts (title, body, user_id) values ('orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam', 'ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam', 47);
insert into Posts (title, body, user_id) values ('a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna', 'maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla', 49);
insert into Posts (title, body, user_id) values ('vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel', 'a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat', 13);
insert into Posts (title, body, user_id) values ('pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat', 'et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim', 5);
insert into Posts (title, body, user_id) values ('donec quis orci eget orci vehicula condimentum curabitur in libero ut', 'sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim', 32);
insert into Posts (title, body, user_id) values ('tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque', 'enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel', 14);
insert into Posts (title, body, user_id) values ('fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis', 'suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis', 46);
insert into Posts (title, body, user_id) values ('ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id', 'sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus', 29);
insert into Posts (title, body, user_id) values ('lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu', 'convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum', 44);
insert into Posts (title, body, user_id) values ('eu orci mauris lacinia sapien quis libero nullam sit amet turpis', 'lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor eu pede', 29);
insert into Posts (title, body, user_id) values ('in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue', 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes', 14);
insert into Posts (title, body, user_id) values ('interdum in ante vestibulum ante ipsum primis in faucibus orci luctus', 'curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus', 4);
insert into Posts (title, body, user_id) values ('eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed', 13);
insert into Posts (title, body, user_id) values ('sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend', 'aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget', 49);
insert into Posts (title, body, user_id) values ('varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla', 'felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at', 16);
insert into Posts (title, body, user_id) values ('elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis', 'sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis', 37);
insert into Posts (title, body, user_id) values ('nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh', 'non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel', 20);
insert into Posts (title, body, user_id) values ('porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus', 'primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit', 34);
insert into Posts (title, body, user_id) values ('platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi', 'volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor', 42);
insert into Posts (title, body, user_id) values ('donec semper sapien a libero nam dui proin leo odio porttitor id', 'viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla', 7);
insert into Posts (title, body, user_id) values ('pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus', 'id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros', 38);
insert into Posts (title, body, user_id) values ('dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et', 'lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas', 20);
insert into Posts (title, body, user_id) values ('integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero', 'tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis', 35);
insert into Posts (title, body, user_id) values ('rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at', 'vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in', 33);
insert into Posts (title, body, user_id) values ('odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla', 'dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id', 23);
insert into Posts (title, body, user_id) values ('tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis', 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo', 18);
insert into Posts (title, body, user_id) values ('libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum', 'sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis', 6);
insert into Posts (title, body, user_id) values ('duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec', 'sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing', 30);
insert into Posts (title, body, user_id) values ('duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend', 'nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor', 32);
insert into Posts (title, body, user_id) values ('nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non', 'augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam', 24);
insert into Posts (title, body, user_id) values ('posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin', 'nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum', 26);
insert into Posts (title, body, user_id) values ('potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis', 'praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet', 11);
insert into Posts (title, body, user_id) values ('curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu', 'platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at', 36);
insert into Posts (title, body, user_id) values ('congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl', 'vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet', 5);
insert into Posts (title, body, user_id) values ('enim blandit mi in porttitor pede justo eu massa donec dapibus duis at', 'est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in', 20);
insert into Posts (title, body, user_id) values ('sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis', 'nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis', 38);
insert into Posts (title, body, user_id) values ('ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam', 'vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia', 26);
insert into Posts (title, body, user_id) values ('vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes', 'magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam', 27);
insert into Posts (title, body, user_id) values ('vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien', 'ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut', 30);
insert into Posts (title, body, user_id) values ('sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', 'convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis', 42);
insert into Posts (title, body, user_id) values ('eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla', 'curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare', 49);
insert into Posts (title, body, user_id) values ('lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat', 'integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna', 16);
insert into Posts (title, body, user_id) values ('tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum', 'semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', 15);
insert into Posts (title, body, user_id) values ('ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla', 'faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec', 24);
insert into Posts (title, body, user_id) values ('tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero', 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu', 11);
insert into Posts (title, body, user_id) values ('pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus', 'ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet', 34);
insert into Posts (title, body, user_id) values ('dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in', 'vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida', 31);
insert into Posts (title, body, user_id) values ('quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam', 'libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus', 16);
insert into Posts (title, body, user_id) values ('integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus', 'odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue', 30);
insert into Posts (title, body, user_id) values ('pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae', 24);
insert into Posts (title, body, user_id) values ('luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis', 'urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla', 44);
insert into Posts (title, body, user_id) values ('sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam', 'adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci', 8);
insert into Posts (title, body, user_id) values ('in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra', 'nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis', 38);
insert into Posts (title, body, user_id) values ('id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus', 'hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio', 48);
insert into Posts (title, body, user_id) values ('volutpat quam pede lobortis ligula sit amet eleifend pede libero', 'nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam', 31);
insert into Posts (title, body, user_id) values ('morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem', 'sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac', 5);
insert into Posts (title, body, user_id) values ('felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed', 'ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non', 39);
insert into Posts (title, body, user_id) values ('adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien', 'curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed', 2);
insert into Posts (title, body, user_id) values ('gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget', 'non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan', 46);
insert into Posts (title, body, user_id) values ('id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus', 'primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut', 2);
insert into Posts (title, body, user_id) values ('eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo', 'id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan', 21);
insert into Posts (title, body, user_id) values ('nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt', 'nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat', 13);
insert into Posts (title, body, user_id) values ('mi integer ac neque duis bibendum morbi non quam nec', 'integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce', 8);
insert into Posts (title, body, user_id) values ('non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus', 'tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede', 6);
insert into Posts (title, body, user_id) values ('donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam', 'in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit', 8);
insert into Posts (title, body, user_id) values ('lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus', 'vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus', 1);
insert into Posts (title, body, user_id) values ('sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio', 'integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus', 47);
insert into Posts (title, body, user_id) values ('imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris', 'nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque', 3);
insert into Posts (title, body, user_id) values ('suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit', 'velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque', 36);
insert into Posts (title, body, user_id) values ('augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit', 'rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut', 21);
insert into Posts (title, body, user_id) values ('quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 'vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a', 32);
insert into Posts (title, body, user_id) values ('nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse', 'volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin', 36);
insert into Posts (title, body, user_id) values ('mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin', 'id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla', 8);
insert into Posts (title, body, user_id) values ('ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam', 'tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus', 10);
insert into Posts (title, body, user_id) values ('eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis', 'pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce', 26);
insert into Posts (title, body, user_id) values ('rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec', 'ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean', 47);
insert into Posts (title, body, user_id) values ('sapien placerat ante nulla justo aliquam quis turpis eget elit', 'quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae', 10);
insert into Posts (title, body, user_id) values ('justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin', 'malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris', 33);
insert into Posts (title, body, user_id) values ('commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum', 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec', 24);
insert into Posts (title, body, user_id) values ('eleifend luctus ultricies eu nibh quisque id justo sit amet', 'consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices', 16);
insert into Posts (title, body, user_id) values ('mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis', 'integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue', 7);
insert into Posts (title, body, user_id) values ('phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl', 'tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a', 20);
insert into Posts (title, body, user_id) values ('lectus in est risus auctor sed tristique in tempus sit', 'id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra', 23);
insert into Posts (title, body, user_id) values ('ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis', 'suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis', 4);
insert into Posts (title, body, user_id) values ('eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper', 'felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in', 18);
insert into Posts (title, body, user_id) values ('sapien a libero nam dui proin leo odio porttitor id consequat in', 'sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla', 5);


